### ISSUE TITLE
[BUG] Hiding an objective doesn't hide it

### ISSUE THREAD

**Issue by scooper4711** [Forien/foundryvtt-forien-quest-log#113]
**Module Version:** v0.5.3

**Describe the bug**
Hiding an objective by pressing the "eye-con" doesn't actually hide it from players. I have all my players configured as "trusted players" and they can still see the hidden objectives.

**To Reproduce**
1. Go to 'quest log"
2. Click on 'new quest' & fill in some info
3. click on new objective. Fill in info and make it hidden.
4. The quest should be "active"
5. log in as a trusted player and view the quest. You can see the objective

**Expected behavior**
Hidden objectives should be visible only to the GM and assistant GMs until such a time as the objective is made visible.

**Screenshots**
<img width="931" alt="Screen Shot 2020-12-29 at 6 39 15 PM" src="https://user-images.githubusercontent.com/1970249/103324543-2cb0ac80-4a05-11eb-9c1f-a45f59348ad3.png">

**Browser:**
 - Chrome

**Foundry Version:** 
0.7.8

**Game System:** 
HarnMaster

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by k-barber** [comment]
@scooper4711 I was having this issue as well until I realized that under the "Manage Quest" tab, the "Allow Players to edit Quest Details" option is **ON** by default, which meant players could both see the hidden objectives, _and_ see text tagged as "Secret" in the quest description. 

I'm assuming that your screenshot is from the player's perspective. I can see that it has the reorder, edit, hide/unhide and delete buttons on the objective, suggesting the players can edit the objectives.

If you turn it off, it should fix the issue

"Allow Players to edit Quest Details" = ON (player's perspective):
![image](https://user-images.githubusercontent.com/44244481/112088632-8fc66100-8b66-11eb-8e62-17364406a1b9.png)

"Allow Players to edit Quest Details" = OFF (player's perspective):
![image](https://user-images.githubusercontent.com/44244481/112088670-a10f6d80-8b66-11eb-8c99-83bc856e99c2.png)

@Forien I don't know if this option is supposed to be on by default or not, but so far every quest I make seems to have it enabled by default. If this is supposed to be off by default this may be a bug. If this is the expected behavior, I think it would probably be best to make this a module setting. Something like "Allow players to edit quests details by default" or so.

Cheers!

**Comment by scooper4711** [comment]
@k-barber  - Thanks!! you nailed it!
