### ISSUE TITLE
Adding the ability to have notes show under the quests

### ISSUE THREAD

**Issue by MaineKnight** [Forien/foundryvtt-forien-quest-log#136]
I DM an in person game so my players never see the quest stuff. It would be useful to be able to click an assigned quest requirement and it would expand to show details/notes about that quest, then click and it would collapse again.

![Suggest](https://github.com/user-attachments/assets/981d103d-c5ad-46e4-9321-4554e580a445)

Flow:
When you click the first quest requirement it would expand to show the details, then when you click it again it would collapse. Same with each quest.

**Comment by typhonrt** [comment]
Hi @MaineKnight...

I'm prefacing this comment as I was the past developer / maintainer of FQL up to this most recent release `0.8.0`, but can provide a response. Any future enhancements will be directed by Forien the original developer of FQL moving forward.

It's certainly great that you find FQL useful for in-person games, however it's challenging to provide a more streamlined user experience (UX) in this case as it is not the main use case / environment of Foundry. While there are no metrics for those that use Foundry / FQL solely for in-person games the percentage is assumed to be rather low if barely registering. 

Normally, when FQL is used in a VTT context any extra notes on the quest that a GM might want to notate goes under the `GM Notes` tab / editor. You are using the main description area that is intended to be publicly viewable in a VTT context for this purpose which is fine, but is not something that can be normally linked to objectives. There are general challenges as well since that field is a rich text editor (RTE) field, so coordinating linking between the RTE and objectives stored in a quest is not something that can be prioritized.

FQL does have a public API that could use a bit better documentation. It's entirely possible to create an additional module that provides a better workflow for in-person games, but still leverages FQL for the main quest management / tracking. This is beyond the scope of FQL itself though.

My guess is that while acknowledged that this enhancement request will not be fulfilled with anything actionable on the FQL side of things.

**Comment by MaineKnight** [comment]
Hi,

Thanks for the message back. It was a feature I had seen in another quest module and found worked well. So thought I would suggest it here as I find this layout a little more usable.
