### ISSUE TITLE
Optional Setting to allow Players to create quests

### ISSUE THREAD

**Issue by Forien** [Forien/foundryvtt-forien-quest-log#19]

**Comment by GameMaker** [comment]
+1 - I'd like my players to use Quest Log to keep their own notes, instead of me boiling everything down to bite-sized clear pieces for them. (And to reduce prep time, etc. on GMs! :)

**Comment by Moerill** [comment]
+1 similar to GameMaker

I'd like my players to (after i possibly created them) modify the quests as they get information or do stuff. Use it more to keep track of what they've done (and still have to do) instead of me saying them what to do.

**Comment by Forien** [comment]
@GameMaker @Moerill would you prefer it being per-quest setting, or global configuration?

**Comment by Moerill** [comment]
i'd prefer it like this:
* allow players to create quests  (let them choose if private or for all. GM can see them always)
* GM Created: set permissions to either read or r/w (all players with access, meaning personal/private quests only by  the person belonging it to)

**Comment by Forien** [comment]
Currently in build for 0.4.0 there is configuration setting allowing players to create (but not edit) quest using Quest Form (so no rewards/personal settings)

So you propose a per-quest checkbox that boils down to "allow players that can access this quest to fully edit it", yes?

**Comment by Moerill** [comment]
i actually just forgot about the rewards :sweat_smile: 

i'm mainly interested in them being able to edit the details and objectives.
Rewards should be set by the gm i think.
so summary as to how i'd envision it:
* Allow players to create quests
* Add setting for GM only to allow players to edit quests
* Let them choose if private (for themself and GM) or open to everyone
* Allow them to modify details and objectives (or maybe make it even finer grained and let gm decide what exactly players are able to modify)
* (Do not let them modify rewards)

**Comment by Forien** [comment]
> Let them choose if private (for themself and GM) or open to everyone

I think that should remain strictly GM setting. To possibly avoid one player grabbing quest for themself. 
And since I want to release 0.4.0 asap, I think that it will be binary at first release (either players can edit everything, or nothing). More precise permissions could be added later.

**Comment by Moerill** [comment]
> Let them choose if private (for themself and GM) or open to everyone

ah meant that setting for when the player creates it (on creation). not later on.

**Comment by GameMaker** [comment]
Good stuff. (Neat to be on a thread with moerill, too, since I'm a MESSy Foundry DM. :)

Personally, I don't use the "rewards" for much more than notekeeping.
I run a game with 1 adult and 5 early teens (12-14), so mostly I'm trying to get THEM in the habit of taking notes. "What are we doing? Ok, we did <that>, what do we do next?"
Right now I have to keep reminding them, or they wander around, so my primary goal is to get them to use this as a sort of public, structured notebook. Everyone can add details, like "He said we have to visit the prince first, remember? We should add that as a step in the quest..."

So _personally_, I don't care much if they can edit the rewards, because I don't think I'll really use those. All I care about is that they can
- create a new quest
- see and edit the "Details" page for any available or in progress quest, at least description and objectives (makes sense to keep the rewards section off-limits if that helps others)
- Add / change / delete objectives
- mark things complete

I agree, probably leave the Manage Quest (which simplifies the whole "take for myself" problem) and of course the GM notes private except to anyone with Assistant GM or above permissions.

Hope that helps - thanks!
