### ISSUE TITLE
Support links in all text boxes.

### ISSUE THREAD

**Issue by SalieriC** [Forien/foundryvtt-forien-quest-log#3]
I'd like to see links (i.e. @Item[Item-Name]) working in all text boxes, including objectives.

**Comment by Forien** [comment]
@SalieriC I am not sure yet how, but I certainly will try to do that :)

**Comment by Forien** [comment]
Implemented Entity linking in tasks (since Description and GM Notes already supported them). 
Works identical to Journal links. Works by names only. Works with spaces in names.
Will be released with next update, probably with some styling adjustments.
![11e01fa151f0d5c9fb414f893a01e92c](https://user-images.githubusercontent.com/11304207/84777006-55310600-afe1-11ea-9ad2-88d97ae934d3.gif)

**Comment by Forien** [comment]
closed by #24
