### ISSUE TITLE
Unable to open the quest log as GM[BUG]

### ISSUE THREAD

**Issue by Pecomica** [Forien/foundryvtt-forien-quest-log#59]
**Module Version:** v0.4.4

**Describe the bug**
Trying to opening the questlog for viewing, editing or adding result in nothing happening

**To Reproduce**
1. Go to 'Journal Entries'
2. Click on 'Quest Log icon at the bottom of the tab'

**Expected behavior**
The quest log to open

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 
0.6.4

**Game System:** 
Pathfinder 1

**Additional context**
Haven't had any issues with opening and editing the quest logs since last foundry update. Only updates I've done since is the mod updates. As a player I can open the quest log and view the quest 'players' have access to, but GM access isn't working.

F12 spit out this error when trying to open the questlog
SyntaxError: An error occurred while rendering QuestLog 4: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.getContent (quest.mjs:367)
    at quest.mjs:390
    at Array.forEach (<anonymous>)
    at Function.getQuests (quest.mjs:389)
    at QuestLog.getData (quest-log.mjs:61)
    at QuestLog._render (foundry.js:3854)
    at QuestLog.render (foundry.js:3824)
    at HTMLButtonElement.<anonymous> (init.mjs:72)
    at HTMLButtonElement.dispatch (jquery.min.js:2)

**Comment by Forien** [comment]
What `error` do you see?

**Comment by Pecomica** [comment]
Error when trying the macro
foundry.js:3826 SyntaxError: An error occurred while rendering QuestLog 4: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.getContent (quest.mjs:367)
    at quest.mjs:390
    at Array.forEach (<anonymous>)
    at Function.getQuests (quest.mjs:389)
    at QuestLog.getData (quest-log.mjs:61)
    at QuestLog._render (foundry.js:3854)
    at QuestLog.render (foundry.js:3824)
    at eval (eval at execute (foundry.js:27593), <anonymous>:4:12)
    at Macro.execute (foundry.js:27593)

**Comment by Forien** [comment]
Ok, seeing your error, I know for a fact that you edited some quest's data via `JournalEntry` UI and that broke the Quests, and by that, Quest Log. If you know which quest you changed, simply delete it. If you don't, you would need to delete all quests. 

Since it only breaks for GM, it's only HIDDEN quest(s) that is/are broken. 

If you want, you can also send me (on Discord) login link and password as a GM/Assistant GM and I can attempt to restore your quests without losing data.

**Comment by Pecomica** [comment]
how do I delete the quests? Looking over the journal entries I don't see any that relates to any of the quests (Only see journal entries that relates to settlements and such). As I can't open the quest log as a GM, I can't see any quests to delete.

**Comment by Forien** [comment]
Then let me also ask you this - did you do anything with Journal Entries like mass export/import? Or maybe you have some module that interacts with Journal Entries?

Because if you don't have Quest Folder visible, it means you didn't actually edit the Quest via Journal's interface, and that makes me wonder what the actual reason of bug is. 

If possible I would like to log into your game and debug.

If you want to fix it yourself, you can go to Module Settings and enable setting that shows the `Quest folder`, then in Journal tab you will see `_fql_quests` folder containing all quests. At least one of them (probably hidden one) is broken.

**Comment by Pecomica** [comment]
Thanks. I got it sorted.
I had a quest called new journal entry. Probably was in the process of making a quest, and tabbed out from the module or foundry and it got saved as a quest entry with out any information in it. 

I remove that one and I can now open the quest log again

**Comment by Forien** [comment]
This is very weird, even with empty form, quest should have saved with name of `New Quest`. I will look into that, in the meantime, I'm closing this issue.

If it ever happens again, please let me know.
