### ISSUE TITLE
Hide Sub Quests

### ISSUE THREAD

**Issue by rinnocenti** [Forien/foundryvtt-forien-quest-log#63]
Sub quests are usually offshoots that often have mission spoilers, so it would be nice if you could "hide" them as tasks.

**Comment by Forien** [comment]
Subquests are by default hidden. They show up when are accepted, conpleted
or failed.

In Quest Log they show up only if accepted.

Or do you mean that you want option to hide them even when in progress etc?


pon., 13 lip 2020, 04:10 użytkownik Renato Innocenti <
notifications@github.com> napisał:

**Comment by rinnocenti** [comment]
as it does not have a visual indication, I thought that the sub quests were not hidden (like the tasks), maybe make this clearer for the GM

**Comment by Forien** [comment]
Thanks for feedback, will keep that in mind

pon., 13 lip 2020, 05:33 użytkownik Renato Innocenti <
notifications@github.com> napisał:

**Comment by xxlbug** [comment]
I have the same problem and foriens statement is not true for me:

- module version 0.4.4
- foundry 0.6.5
- gm in one chrome window, test player in a second, incognito one

1. the main and subquest is hidden from the player
2. make the main quest available and set "in progress" since i don't use the available quest option
3. the test player can see the main quest in the quest log, open it, see the subquest, open it then and can see the quest giver (task and rewards are hidden as set from me)

any suggestions?
